version: '2'
services:
  database:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]

  proxy:
    image: nginx:1.13.6-alpine
    ports:
      - "8443:443"
    volumes:
      - ${PWD}:/etc/nginx/conf.d
      - ${PWD}/tls/nginx.key:/etc/nginx
    depends_on: [ conjur ]

  client:
    image: cyberark/conjur-cli:5
    depends_on: [ proxy ]
    entrypoint: sleep
    command: infinity
